### ISSUE TITLE
Descripción de los puntos y enlace a la tabla

### ISSUE THREAD

**Issue by martinszy** [datosgobar/mapa-gob-abierto#2]
Cada punto debería desplegar un globo con la información detallada de la iniciativa.
Y en la descripción del mapa debería estar el enlace a la tabla .... o al readme donde estan las tablas.

**Comment by pilimayora** [comment]
Hola @martinszy .
1. Cada iniciativa despliega un pop up con sus detalles haciendo click en ella. Podés ver: el tema, el nombre de la organización, la ciudad y la web.
2. Al costado izquierdo del mapa hay un desplegable que lleva a la cuenta pública de Datos Argentina en CARTO. Ahí podés encontrar los dos datasets públicos utilizados. También podés acceder a las planillas públicas siguiendo los links del README de este repositorio.
